// flow-typed signature: d38c0ee102dc13f85fd7fa1dd07efacd
// flow-typed version: <<STUB>>/react-native_vx.x.x/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native' {
  declare module.exports: any;
}
